config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/about'
  resources :vacancies 
  resources :events 
  resources :news 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'amharic-home'=> "static_pages#amharic_home"
  get 'oromia-home' =>"static_pages#oromo_home"
  root to: "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
 has_one_attached :image
end

app/models/news.rb
class News < ApplicationRecord
	has_one_attached :image
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @search = Event.search(params[:q])
    @events = @search.result.order("created_at DESC").page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @search = News.search(params[:q])
    @news = @search.result.order("created_at DESC").page(params[:page])
  end

  def show
    @new = News.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def amharic_home
  end

  def oromo_home
  end

  def about
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  
  def index
    @search = Vacancy.search(params[:q])
    @vacancies = @search.result.order("created_at DESC").page(params[:page])
  end

  def show
    @vacancy = Vacancy.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vacancy_helper.rb
module VacancyHelper
end

app/views/events/index.html.erb
<%provide(:title, "events")%>

<%= render 'layouts/nav_bar'%>
<main id="main" style="margin-top: 110px;">

	<!-- ======= Breadcrumbs ======= -->
	<section class="breadcrumbs">
		<div class="container">

			<ol>
				<li><a href="index.html">Home</a></li>
				<li>events</li>
			</ol>
			<h2>events</h2>

		</div>
	</section><!-- End Breadcrumbs -->

	<!-- ======= Blog Section ======= -->
	<section id="blog" class="blog">
		<div class="container" data-aos="fade-up">
			<div class="row">

				<div class="col-lg-12 entries">
					<div class="row">
						<% @events.each do |event|%>
							<div class="col-12 col-md-4">
								<article class="entry">
									<div class="entry-img">
										<%= image_tag event.image, alt: "", class: "img-fluid"%>
									</div>
									<h2 class="entry-title">
										<%= link_to event.title, event_path(event) %>
									</h2>
									<!-- <div class="entry-meta">
										<ul>
											<li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">John Doe</a></li>
											<li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
											<li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">12 Comments</a></li>
										</ul>
									</div> -->
									<div class="entry-content">
										<p>
											<%= event.overview%>
										</p>
										<div class="read-more">
											<%= link_to "Read More", event_path(event) %>
										</div>
									</div>

								</article><!-- End blog entry -->
							</div>
						<%end%>
					</div>

					<!-- <div class="blog-pagination">
						<ul class="justify-content-center">
							<li><a href="#">1</a></li>
							<li class="active"><a href="#">2</a></li>
							<li><a href="#">3</a></li>
						</ul>
					</div> -->
				</div><!-- End blog entries list -->
			</div>

		</div>
	</section><!-- End Blog Section -->

</main><!-- End #main -->

app/views/events/show.html.erb
<%provide(:title, "Events")%>

<%= render 'layouts/nav_bar'%>
<main id="main" style="margin-top: 110px;">

	<!-- ======= Breadcrumbs ======= -->
	<section class="breadcrumbs">
		<div class="container">

			<ol>
				<li><a href="index.html">Home</a></li>
				<li><a href="blog.html">Events</a></li>
				<li><%= @event.title%></li>
			</ol>
			<h2><%= @event.title%></h2>

		</div>
	</section><!-- End Breadcrumbs -->

	<!-- ======= Blog Single Section ======= -->
	<section id="blog" class="blog">
		<div class="container" data-aos="fade-up">

			<div class="row">

				<div class="col-lg-12 entries">

					<article class="entry entry-single">

						<div class="entry-img">
							<%= image_tag "gift17.jpg", alt: "", class: "img-fluid"%>
						</div>

						<h2 class="entry-title">
							<%= link_to @event.title, event_path(@event) %>
						</h2>
						<div class="entry-content">
							<p>
								<%= @event.body %>
							</p>
						</div>
					</div><!-- End blog entries list -->
				</div>

			</div>
		</section><!-- End Blog Single Section -->

  </main><!-- End #main -->

app/views/layouts/_footer.html.erb
  <div class="footer-top">
   <div class="container-fluid">
    <div class="row justify-content-center">
     <div class="col-xl-10">
      <div class="row">

       <div class="col-lg-3 col-md-6 footer-links">
        <h4>Useful Links</h4>
        <ul>
         <li><i class="bx bx-chevron-right"></i> <a href="assets/1.pdf">Download Construction Permit Instructions</a></li>
         <li><i class="bx bx-chevron-right"></i> <a href="assets/1.pdf">Download Application Forms</a></li>
         <li><i class="bx bx-chevron-right"></i> <a href="assets/1.pdf">Download Requirements</a></li>
         <li><i class="bx bx-chevron-right"></i> <a href="assets/1.mp4" download> Download Tutorial  </a></li>

       </ul>
     </div>


     <div class="col-lg-3 col-md-6 footer-contact">
      <h4>Contact Us</h4>
      <p>
       Lem hotel  <br>
       22 Road,MA Building<br>
       Addis Ababa <br><br>
       <strong>Phone:</strong> +2519112233<br>
       <strong>Email:</strong> constuctionpermit@gmail.com<br>
     </p>

   </div>

   <div class="col-lg-3 col-md-6 footer-info">
    <h3>About Us</h3>
    <p>We are a govermental office business goes through in order to construct a commercial building premise, ranging from land authentication to acquiring necessary consents and permits, to final inspection once the construction is complete. Government organizations involved in this journey to provide the required services</p>
    <div class="social-links mt-3">
     <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
     <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
     <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
     <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
     <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
   </div>
 </div>

</div>
</div>
</div>
</div>
</div>

<div class="container">
 <div class="copyright">
  &copy; Copyright <strong><span>Addis Ababa Construction Permit and Control Autority</span></strong>. All Rights Reserved
</div>
<div class="credits">
  <!-- All the links in the footer should remain intact. -->
  <!-- You can delete the links only if you purchased the pro version. -->
  <!-- Licensing information: https://bootstrapmade.com/license/ -->
  <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/hidayah-free-simple-html-template-for-corporate/ -->
  Designed by <a href="https://bootstrapmade.com/">IT Department of AACP</a>
</div>
</div>

app/views/layouts/_nav_bar.html.erb
<!-- ======= Header ======= -->
<header id="header" class="fixed-top header-inner-pages">
 <div class="container d-flex align-items-center justify-content-between">
  <%= image_tag "logo_new.png", size: "70x70", align:"left"%>
  <h6 style="color:white;">Addis Ababa Construction Permit and Control Autority</h6>
  <!-- Uncomment below if you prefer to use an image logo -->
  <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

  <nav id="navbar" class="navbar">
   <ul>
    <li><a class="nav-link scrollto active" href="https://aacp.gov.et/#hero">Home</a></li>
    <li><a class="nav-link scrollto" href="https://aacp.gov.et/#about">How to  Apply</a></li>
    <li><a class="nav-link scrollto" href="https://aacp.gov.et/#services">Services</a></li>
    <li><a class="nav-link  scrollto" href="https://aacp.gov.et/#portfolio">Gallery</a></li>
    <li><a class="nav-link scrollto" href="https://aacp.gov.et/#team">Managment Team</a></li>
    <li class="dropdown"><a href="/"><span>Announcements</span> <i class="bi bi-chevron-down"></i></a>
      <ul>
        <li><%= link_to "News", news_index_path%></li>
        <li><%= link_to "Events", events_path%></li>
        <li><%= link_to "Vacancy", vacancies_path%></li>
        <li><a href="#">Tenders</a></li>
      </ul>
    </li>
    <li class="dropdown"><a href="/"><span>Resources</span> <i class="bi bi-chevron-down"></i></a>
     <ul>
      <li><a href="#https://drive.google.com/file/d/1xncfxGnl0fr8vOpRd4MIx7ux7UAjcBkq/view?usp=sharing">Application Forms</a></li>
      <li><a href="#https://drive.google.com/file/d/1jj2WUjbczTWQ5zcXXkA9DKU7LNNwLNjQ/view?usp=sharing">Instructions</a></li>
      <li><a href="#https://drive.google.com/file/d/1hinjsSWX0AQxF84KOxB8LQpJ4OefcAyr/view?usp=sharing">Requirements</a></li>
      <li><a href="https://www.youtube.com/watch?v=UNpCbDuDuLE">Tutorial videos</a></li>
      <li><a href="https://drive.google.com/file/d/1djawfKIIKAlxQSmPSuLamaBs_5arR2Cb/view">Structure</a></li>
    </ul>
  </li>
  <li><a class="nav-link scrollto" href="https://aacp.gov.et/#contact">Contact</a></li>
  <li class="dropdown"><a href="/"><span>Language</span> <i class="bi bi-chevron-down"></i></a>
   <ul>
    <li><%= link_to "English", root_path%></li>
    <li><%= link_to "Amharic", amharic_home_path%></li>
    <li><%= link_to "Oromic", oromia_home_path%></li>
  </ul>
</ul>
<i class="bi bi-list mobile-nav-toggle"></i>
</nav><!-- .navbar -->

</div>
</header><!-- End Header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AACP - Addis Ababa Construction Permit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
    <!-- <div id="preloader"></div> -->
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  </body>
</html>

app/views/news/index.html.erb
<%provide(:title, "News")%>

<%= render 'layouts/nav_bar'%>
<main id="main" style="margin-top: 110px;">

	<!-- ======= Breadcrumbs ======= -->
	<section class="breadcrumbs">
		<div class="container">

			<ol>
				<li><a href="index.html">Home</a></li>
				<li>News</li>
			</ol>
			<h2>News</h2>

		</div>
	</section><!-- End Breadcrumbs -->

	<!-- ======= Blog Section ======= -->
	<section id="blog" class="blog">
		<div class="container" data-aos="fade-up">
			<div class="row">

				<div class="col-lg-12 entries">
					<div class="row">
						<% @news.each do |news|%>
							<div class="col-12 col-md-4">
								<article class="entry">
									<div class="entry-img">
										<%= image_tag news.image, alt: "", class: "img-fluid"%>
									</div>
									<h2 class="entry-title">
										<%= link_to news.title, news_path(news) %>
									</h2>
									<!-- <div class="entry-meta">
										<ul>
											<li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">John Doe</a></li>
											<li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">Jan 1, 2020</time></a></li>
											<li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">12 Comments</a></li>
										</ul>
									</div> -->
									<div class="entry-content">
										<p>
											<%= news.overview%>
										</p>
										<div class="read-more">
											<%= link_to "Read More", news_path(news) %>
										</div>
									</div>

								</article><!-- End blog entry -->
							</div>
						<%end%>
					</div>

					<!-- <div class="blog-pagination">
						<ul class="justify-content-center">
							<li><a href="#">1</a></li>
							<li class="active"><a href="#">2</a></li>
							<li><a href="#">3</a></li>
						</ul>
					</div> -->
				</div><!-- End blog entries list -->
			</div>

		</div>
	</section><!-- End Blog Section -->

</main><!-- End #main -->

app/views/news/show.html.erb
<%provide(:title, "News")%>

<%= render 'layouts/nav_bar'%>
<main id="main" style="margin-top: 110px;">

	<!-- ======= Breadcrumbs ======= -->
	<section class="breadcrumbs">
		<div class="container">

			<ol>
				<li><a href="index.html">Home</a></li>
				<li><a href="blog.html">News</a></li>
				<li><%= @new.title%></li>
			</ol>
			<h2><%= @new.title%></h2>

		</div>
	</section><!-- End Breadcrumbs -->

	<!-- ======= Blog Single Section ======= -->
	<section id="blog" class="blog">
		<div class="container" data-aos="fade-up">

			<div class="row">

				<div class="col-lg-12 entries">

					<article class="entry entry-single">

						<div class="entry-img">
							<%= image_tag @new.image, alt: "", class: "img-fluid"%>
						</div>

						<h2 class="entry-title">
							<%= link_to @new.title, news_path(@new) %>
						</h2>
						<div class="entry-content">
							<p>
								<%= @new.body %>
							</p>
						</div>
					</div><!-- End blog entries list -->
				</div>

			</div>
		</section><!-- End Blog Single Section -->

  </main><!-- End #main -->

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/vacancies/index.html.erb
<%provide(:title, "Vacancies")%>

<%= render 'layouts/nav_bar'%>
<main id="main">

<section class="hero-section-page-title overlay bg-cover" data-background="page-title.jpg">
<style scoped>
.on-the-fly-behavior {
    margin-top: 145px;
}
@media (max-width: 1000px) {
    .on-the-fly-behavior {
        margin-top: 175px;
    }
}
</style>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mt-2">
        <ul class="list-inline custom-breadcrumb">
          <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="courses.html">Open Vacancies</a></li>
          <li class="list-inline-item text-white h3 font-secondary "></li>
        </ul>
        <!-- <p class="text-lighten">Our courses offer a good compromise between the continuous assessment favoured by some universities and the emphasis placed on final exams by others.</p> -->
      </div>
    </div>
  </div>
</section>

<div class="content clearfix element content bg-white"><div class="list-group">
  <li class="list-group-item list-group-item-action flex-column align-items-start active bg-white ">
      <h2 class="h1-responsive font-weight-bold text-center my-3 bg-white">የሥራ ማስታወቂያዎች</h2>

        <div class="row my-3">
            <div class="col-lg-6  col-sm-12 offset-lg-3">
              <%= search_form_for(@search, html: { class: "input-group form-sm form-1 pl-0" }) do |f| %>
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-text1"><i class="fa fa-search text-dark"
                    aria-hidden="true"></i></span>
                  </div>
                   
                    <%= f.search_field :title_or_catagory_cont, class: "form-control my-0 py-1",placeholder: "Search by Vacancy name or catagory"   %>
                    
                  
                  <!-- <input class="form-control my-0 py-1" type="text" placeholder="Search" aria-label="Search"> -->
              <% end %>
            </div>
        </div> 
  </li>
 
  <% @vacancies.each do |v|%>
    <%= link_to vacancy_path(v.id), class: "list-group-item list-group-item-action flex-column align-items-start col-lg-11 mr-5 mb-5 pl ml-5 z-2 " do %>
      <div class="d-flex w-100 justify-content-between">
        <h4 class="mb-2 h4 font-weight-bold h4-responsive"><%= v.title%></h4>
        <small><%= time_ago_in_words(v.deadline) %> Left</small>
      </div>
      <p class="mb-2 font-weight-bold"><%= v.organization_name%></p>
      <p class=" mb-2 text-darken-3 lighten-3"><%= v.city%></p>
      <p class="grey-text text-darken-3 lighten-3"><span class="fa fa-briefcase ml-1">
        
      </span> <%= v.employment_type%></p>
    <%end%>
  <%end%>

</div>
    <div class=" text-center my-5">
        <%= paginate @vacancies %> 
        <%= page_entries_info @vacancies %>
    </div>
</div>

</main>

app/views/vacancies/show.html.erb
<main id="main">
<%provide(:title, "#{@vacancy.title}")%>

<section class="hero-section-page-title overlay bg-cover" data-background="../page-title.jpg">
<style scoped>
.on-the-fly-behavior {
    margin-top: 145px;
}
@media (max-width: 1000px) {
    .on-the-fly-behavior {
        margin-top: 175px;
    }
}
</style>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mt-2">
        <ul class="list-inline custom-breadcrumb">
          <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="courses.html">Vacancies</a></li>
          <li class="list-inline-item text-white h3 font-secondary "></li>
        </ul>
        <p class="text-lighten">Our courses offer a good compromise between the continuous assessment favoured by some universities and the emphasis placed on final exams by others.</p>
      </div>
    </div>
  </div>
</section>
<div class="list-group" style="
    margin-top: 50px !important;
">
  	<div class="mb-2 ml-5">
		  <li class="list-group-item ml-5">
		    <h3 class="h2-responsive font-weight-bold text-center my-3"><strong><%= @vacancy.title%></strong></h3>
		  </li>
		  <li class="list-group-item ml-5">
		  	<h6>Job By : <%= @vacancy.organization_name%></h6>

		  	<span class="text-darken-3 lighten-3">City: </span><span class="grey-text text-darken-3 lighten-3">  &ensp;<%= @vacancy.city%> </span><br>
		  	<span class="text-darken-3 lighten-3">Catagory: </span><span class="grey-text text-darken-3 lighten-3"> &ensp;<%= @vacancy.catagory %>  </span><br>
		  	<span class="text-darken-3 lighten-3">Career Level: </span><span class="grey-text text-darken-3 lighten-3">&ensp;<%= @vacancy.career_level%> </span><br>
		  	<span class="text-darken-3 lighten-3">Salary:</span><span class="grey-text text-darken-3 lighten-3">  &ensp;<%= @vacancy.salary%> ETB </span><br>
		  	<span class="text-darken-3 lighten-3">Employment Type:</span><span class="grey-text text-darken-3 lighten-3">  &ensp;<%= @vacancy.employment_type%> </span><br>
		  	<!-- fix the deadline and created at date by making it to count the dates -->
		  	<span class="text-darken-3 lighten-3">Deadline:</span><span class="grey-text text-darken-3 
		  	lighten-3">  &ensp;<%= time_ago_in_words(@vacancy.deadline) %> Left</span><br> 
		  	<span class="text-darken-3 lighten-3">Created At:</span><span class="grey-text text-darken-3 lighten-3">  &ensp;<%= time_ago_in_words(@vacancy.created_at) %> ago</span><br>
		  </li>
		  <li class="list-group-item ml-5">
		  	<h6><strong>Job Description</strong></h6>
		  	<p class="grey-text text-darken-3 lighten-3"> <%= @vacancy.description%> </p>

		  </li>
		  <li class="list-group-item ml-5">
		  	<h6><strong>Job Requiremnt</strong></h6>
		  	<p class="grey-text text-darken-3 lighten-3"> <%= @vacancy.requirement %> </p>

		  </li>

		  <li class="list-group-item ml-5">
		  	<small class="grey-text mb-3">Organization Information</small><br>

		  	<span class="text-darken-3 lighten-3">Website: </span><span class="grey-text text-darken-3 lighten-3">  &ensp;<%= @vacancy.website%> </span><br>
		  	<span class="text-darken-3 lighten-3">Email: </span><span class="grey-text text-darken-3 lighten-3"> &ensp;<%= @vacancy.email %>  </span><br>
		  	<span class="text-darken-3 lighten-3">Address: </span><span class="grey-text text-darken-3 lighten-3">&ensp;<%= @vacancy.address_1%> </span><br>
		  	<span class="text-darken-3 lighten-3">Phone Number:</span><span class="grey-text text-darken-3 lighten-3">  &ensp;<%= @vacancy.phone_number_1%></span><br>
		  	<span class="text-darken-3 lighten-3">Address 2: </span><span class="grey-text text-darken-3 lighten-3">&ensp;<%= @vacancy.address_2%> </span><br>
		  	<span class="text-darken-3 lighten-3">Phone Number 2:</span><span class="grey-text text-darken-3 lighten-3">  &ensp;<%= @vacancy.phone_number_2%></span><br>

		  	
		  </li>
	  </div>
</div>
</main>